In [126]:
import numpy as np 
import os 
import pandas as pd 
list1 = [1,4,2,10,5]
np_arr = np.array(list1)/10
np_arr
path = os.getcwd()
print(path)

C:\Users\004FME744


In [4]:
type(np_arr)

numpy.ndarray

In [6]:
np.shape(np_arr)

(7,)

In [7]:
np_arr.shape

(7,)

In [13]:
two_d = np.array([[1,2,3,4,1],[1,48,1,3,5]])
two_d

array([[ 1,  2,  3,  4,  1],
       [ 1, 48,  1,  3,  5]])

In [19]:
l1 = [1,2,3,4,5]
l2 = [4,5,6,7,10]
x = np.array([l1,l2])
x

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7, 10]])

In [20]:
x.shape

(2, 5)

In [35]:
#slicing and indexing in numpy
a1 = np.array([1,3,4,2,8])
a2 = np.array([[1,1,1,1,1]])
print(type(a1), type(a2), a1.shape, a2.shape)
a1

<class 'numpy.ndarray'> <class 'numpy.ndarray'> (5,) (1, 5)


array([1, 3, 4, 2, 8])

In [34]:
a1[1:]

array([3, 4, 2, 8])

In [29]:
a2[0][3]

1

In [68]:
a1

1

In [37]:
a1[::-1]

array([8, 2, 4, 3, 1])

In [38]:
a2

array([[1, 1, 1, 1, 1]])

In [41]:
arr1 = np.array([[1,2,3,4,6,7,8],[10,4,2,5,10,4,1]])
arr1

array([[ 1,  2,  3,  4,  6,  7,  8],
       [10,  4,  2,  5, 10,  4,  1]])

In [42]:
arr1.shape

(2, 7)

In [46]:
arr1[1:,2:]

array([[ 2,  5, 10,  4,  1]])

In [49]:
arr2 = np.array([[10,20,4,1,5], [1,4,2,5,0],[4,2,19,5,1]])
arr2

array([[10, 20,  4,  1,  5],
       [ 1,  4,  2,  5,  0],
       [ 4,  2, 19,  5,  1]])

In [50]:
arr2[1:,2:]

array([[ 2,  5,  0],
       [19,  5,  1]])

In [54]:
arr2[1,3]

5

In [55]:
arr2

array([[10, 20,  4,  1,  5],
       [ 1,  4,  2,  5,  0],
       [ 4,  2, 19,  5,  1]])

In [56]:
arr2[::-1,]

array([[ 4,  2, 19,  5,  1],
       [ 1,  4,  2,  5,  0],
       [10, 20,  4,  1,  5]])

In [57]:
arr1


array([[ 1,  2,  3,  4,  6,  7,  8],
       [10,  4,  2,  5, 10,  4,  1]])

In [58]:
list1

[1, 4, 2, 10, 5, 1, 10]

In [66]:
a1>1

False

In [67]:
a1>1

False

In [69]:
t1 = np.array([1,4,2,5,6])
t1>2

array([False,  True, False,  True,  True])

In [70]:
t1>=2

array([False,  True,  True,  True,  True])

In [71]:
arr2

array([[10, 20,  4,  1,  5],
       [ 1,  4,  2,  5,  0],
       [ 4,  2, 19,  5,  1]])

In [73]:
arr2[arr2>5]

array([10, 20, 19])

In [74]:
#array manipulation functions
arr1

array([[ 1,  2,  3,  4,  6,  7,  8],
       [10,  4,  2,  5, 10,  4,  1]])

In [77]:
arr2

array([[10, 20,  4,  1,  5],
       [ 1,  4,  2,  5,  0],
       [ 4,  2, 19,  5,  1]])

In [78]:
np_arr

array([0.1, 0.4, 0.2, 1. , 0.5, 0.1, 1. ])

In [88]:
k1 = np.array([1,2,3,4,5,6,4,2,2])
k1

array([1, 2, 3, 4, 5, 6, 4, 2, 2])

In [80]:
arr2.shape

(3, 5)

In [89]:
np.reshape(k1,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [4, 2, 2]])

In [90]:
k1

array([1, 2, 3, 4, 5, 6, 4, 2, 2])

In [91]:
arr1

array([[ 1,  2,  3,  4,  6,  7,  8],
       [10,  4,  2,  5, 10,  4,  1]])

In [92]:
np.ndarray.flatten(arr1) #=np.ravel(arr1)

array([ 1,  2,  3,  4,  6,  7,  8, 10,  4,  2,  5, 10,  4,  1])

In [93]:
np.ravel(arr1)

array([ 1,  2,  3,  4,  6,  7,  8, 10,  4,  2,  5, 10,  4,  1])

In [96]:
ar1 = np.array([[1,1,1],[2,2,2]])
print(ar1.shape,'\n',ar1)

(2, 3) 
 [[1 1 1]
 [2 2 2]]


In [97]:
ar2 = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(ar2.shape,'\n',ar2)


(3, 3) 
 [[3 3 3]
 [4 4 4]
 [5 5 5]]


In [100]:
np.concatenate((ar1,ar2),axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [102]:
ar1

array([[1, 1, 1],
       [2, 2, 2]])

In [103]:
np.transpose(ar1)

array([[1, 2],
       [1, 2],
       [1, 2]])

In [104]:
ar1.transpose()

array([[1, 2],
       [1, 2],
       [1, 2]])

In [105]:
np.sort(ar1,axis=1)

array([[1, 1, 1],
       [2, 2, 2]])

In [106]:
#array creation function 
np.full((2,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [107]:
np.full((5,5),fill_value=1,dtype=np.longdouble)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float64)

In [109]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [110]:
np.arange(0,12,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [113]:
np.linspace(0,100,num=25).reshape(5,5)

array([[  0.        ,   4.16666667,   8.33333333,  12.5       ,
         16.66666667],
       [ 20.83333333,  25.        ,  29.16666667,  33.33333333,
         37.5       ],
       [ 41.66666667,  45.83333333,  50.        ,  54.16666667,
         58.33333333],
       [ 62.5       ,  66.66666667,  70.83333333,  75.        ,
         79.16666667],
       [ 83.33333333,  87.5       ,  91.66666667,  95.83333333,
        100.        ]])

In [117]:
np.random.rand(2,10)

array([[0.38888386, 0.38885705, 0.49756117, 0.65808227, 0.18335784,
        0.8711537 , 0.32138263, 0.66388589, 0.3450993 , 0.03518042],
       [0.72987233, 0.9829286 , 0.06889351, 0.55827081, 0.80894233,
        0.52875813, 0.19411812, 0.16040749, 0.28936364, 0.4015156 ]])

In [119]:
np.random.randint(-20,20,(3,3))

array([[-13,   4,  -1],
       [ -2, -13,  12],
       [ -8,  11, -11]])

In [120]:
np.random.randint(2,50)

43

In [121]:
# np.mean(), np.sum(),np.amax(), np.amin(),np.cusum()->cummulative sum,
ar1


array([[1, 1, 1],
       [2, 2, 2]])

In [129]:
ar1.cumsum(axis=1)

array([[1, 2, 3],
       [2, 4, 6]])

In [135]:
#IO funciton in numpy 
x = np.loadtxt('file.txt', delimiter=',', usecols=(1),skiprows=1)
x

FileNotFoundError: file.txt not found.

NameError: name 'os' is not defined